export type CertificateCategory =
  | "programacao"
  | "backend"
  | "dados"
  | "ia"
  | "cloud"
  | "service-desk"
  | "redes"
  | "banco-de-dados"
  | "git-github"
  | "devops"
  | "carreira"
  | "outros";

// "curso"  = curso, trilha ou formação completa e autocontida
// "modulo" = aula/módulo individual real, dentro de uma trilha maior
// "extra"  = live, questionário, material complementar, semana, desafio,
//            avaliação, onboarding/encerramento — conteúdo de apoio, não o
//            curso em si (recebe menos destaque visual na página)
export type CertificateKind = "curso" | "modulo" | "extra";

export type Certificate = {
  name: string;
  institution: string;
  // Data exatamente como registrada na origem (ex.: "20/08/2026 22:37").
  // Mantida como texto livre de propósito — não reformatada nem reinterpretada.
  date: string;
  description?: string;
  url?: string;
  category: CertificateCategory;
  kind: CertificateKind;
  // true = aparece na seção "Em destaque" (TI, Back-End, Python, SQL, IA, Service Desk)
  featured?: boolean;
  workloadHours?: number;
};

/**
 * Registros reais de cursos e certificados de conclusão da plataforma DIO,
 * fornecidos por Uanderson Martins. Nomes e datas são reproduzidos
 * exatamente como registrados na origem — nada foi inventado, resumido
 * ou reformatado.
 *
 * IMPORTANTE:
 * - Estes são certificados de CONCLUSÃO DE CURSO na DIO, não certificações
 *   oficiais de fabricante (Microsoft, AWS, etc.), exceto quando indicado.
 * - "AZ-204" e "AI-900" nesta lista são cursos/simulados PREPARATÓRIOS para
 *   essas certificações Microsoft — NÃO representam a certificação oficial
 *   obtida. Não trate como tal em nenhuma parte do site.
 * - Nenhuma URL de certificado foi incluída: a plataforma DIO indica
 *   "BAIXAR CERTIFICADO" como disponibilidade do certificado dentro da
 *   própria plataforma, não como um link público — por isso `url` fica
 *   vazio em todos os registros da DIO.
 * - Duplicatas exatas (mesmo nome e mesma data, presentes na exportação
 *   original da plataforma) foram removidas. Nenhum registro real foi
 *   descartado por ser um módulo, semana ou conteúdo menor.
 */
export const certificates: Certificate[] = [
  // --- Curso em Vídeo (fora da DIO, registrado separadamente) ---
  {
    name: "Algoritmos e Lógica de Programação",
    institution: "Curso em Vídeo",
    date: "30/03/2026 00:54", // última atividade registrada; curso 100% concluído
    description: "Curso de 40 horas sobre algoritmos e lógica de programação, concluído 100%.",
    category: "programacao",
    kind: "curso",
    featured: true,
    workloadHours: 40,
  },

  // --- Registros DIO (2024-2026), na ordem em que aparecem no histórico oficial ---
  {
    name: "Aceleração Randstad - Service Desk",
    institution: "DIO",
    date: "20/08/2026 22:37",
    category: "service-desk",
    kind: "curso",
    featured: true,
  },
  {
    name: "Questionário: Aceleração Randstad - Service Desk",
    institution: "DIO",
    date: "20/08/2026 22:37",
    category: "service-desk",
    kind: "extra",
  },
  {
    name: "Introdução a Redes",
    institution: "DIO",
    date: "20/08/2026 20:18",
    category: "redes",
    kind: "curso",
  },
  {
    name: "Comandos Essenciais de CMD na Prática",
    institution: "DIO",
    date: "19/08/2026 20:22",
    category: "redes",
    kind: "modulo",
  },
  {
    name: "Service Desk: do Suporte Reativo ao Atendimento Estratégico",
    institution: "DIO",
    date: "19/08/2026 14:17",
    category: "service-desk",
    kind: "curso",
    featured: true,
  },
  {
    name: "Live de Abertura Aceleração Randstad Service Desk",
    institution: "DIO",
    date: "19/08/2026 12:15",
    category: "service-desk",
    kind: "extra",
  },
  {
    name: "Boas vindas à Aceleração Randstad - Service Desk",
    institution: "DIO",
    date: "13/08/2026 16:57",
    category: "service-desk",
    kind: "extra",
  },
  {
    name: "DIO Campus Expert | Turma 15",
    institution: "DIO",
    date: "08/08/2026 11:49",
    category: "outros",
    kind: "extra",
  },
  {
    name: "Luizalabs - Back-end com Python - 2º Edição",
    institution: "DIO",
    date: "13/07/2026 17:05",
    category: "backend",
    kind: "curso",
    featured: true,
  },
  {
    name: "Treinando uma IA de Aprendizagem: Explore o Poder do NotebookLM",
    institution: "DIO",
    date: "13/07/2026 17:05",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "IA para Acelerar o Desenvolvimento",
    institution: "DIO",
    date: "13/07/2026 17:05",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Utilizando Copilotos de Desenvolvimento de Software",
    institution: "DIO",
    date: "13/07/2026 13:21",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Fundamentos da IA Moderna: Machine Learning, LLMs, IA Generativa e Agentes",
    institution: "DIO",
    date: "09/07/2026 12:01",
    category: "ia",
    kind: "curso",
    featured: true,
  },
  {
    name: "Criando sua API Bancária Assíncrona com FastAPI",
    institution: "DIO",
    date: "08/07/2026 13:43",
    category: "backend",
    kind: "modulo",
  },
  {
    name: "APIs Modernas com FastAPI do Zero ao Deploy",
    institution: "DIO",
    date: "08/07/2026 13:43",
    category: "backend",
    kind: "curso",
    featured: true,
  },
  {
    name: "Deploy de uma API FastAPI Assíncrona",
    institution: "DIO",
    date: "08/07/2026 11:31",
    category: "backend",
    kind: "modulo",
  },
  {
    name: "Testando APIs RESTful Assíncronas em FastAPI",
    institution: "DIO",
    date: "06/07/2026 14:05",
    category: "backend",
    kind: "modulo",
  },
  {
    name: "Autenticação e Autorização em FastAPI",
    institution: "DIO",
    date: "06/07/2026 13:18",
    category: "backend",
    kind: "modulo",
  },
  {
    name: "Manipulação de Dados com FastAPI Assíncrono",
    institution: "DIO",
    date: "06/07/2026 11:40",
    category: "backend",
    kind: "modulo",
  },
  {
    name: "Semana 06 - DIO Campus Expert | Turma 16",
    institution: "DIO",
    date: "04/07/2026 12:34",
    category: "outros",
    kind: "extra",
  },
  {
    name: "Aumentando a Autoridade do seu Perfil Profissional",
    institution: "DIO",
    date: "04/07/2026 12:34",
    category: "carreira",
    kind: "modulo",
  },
  {
    name: "Explorando Banco de Dados Relacionais com Python DB API",
    institution: "DIO",
    date: "25/06/2026 15:01",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Primeiros passos com FastAPI",
    institution: "DIO",
    date: "23/06/2026 13:13",
    category: "backend",
    kind: "modulo",
  },
  {
    name: "Semana 05 - DIO Campus Expert | Turma 16",
    institution: "DIO",
    date: "21/06/2026 14:26",
    category: "outros",
    kind: "extra",
  },
  {
    name: "Desafio 02: Escalando Oportunidades com seu Portfólio de Projetos",
    institution: "DIO",
    date: "21/06/2026 14:26",
    category: "carreira",
    kind: "extra",
  },
  {
    name: "Portfólio para Acelerar sua Carreira em Tech",
    institution: "DIO",
    date: "21/06/2026 14:10",
    category: "carreira",
    kind: "modulo",
  },
  {
    name: "Introdução ao FastAPI para APIs RESTful Assíncronas",
    institution: "DIO",
    date: "19/06/2026 14:32",
    category: "backend",
    kind: "modulo",
  },
  {
    name: "Estruturando o seu Portfólio para Decolar a sua Carreira!",
    institution: "DIO",
    date: "16/06/2026 02:29",
    category: "carreira",
    kind: "modulo",
  },
  {
    name: "Semana 04 - DIO Campus Expert | Turma 16",
    institution: "DIO",
    date: "16/06/2026 02:29",
    category: "outros",
    kind: "extra",
  },
  {
    name: "Conseguindo seu Primeiro Freelance em Tecnologia",
    institution: "DIO",
    date: "16/06/2026 02:29",
    category: "carreira",
    kind: "modulo",
  },
  {
    name: "Introdução a Aplicações Rest",
    institution: "DIO",
    date: "12/06/2026 15:25",
    category: "backend",
    kind: "modulo",
  },
  {
    name: "Modelando o Sistema Bancário em POO com Python",
    institution: "DIO",
    date: "12/06/2026 13:57",
    category: "programacao",
    kind: "modulo",
  },
  {
    name: "Python Orientado a Objetos na Prática",
    institution: "DIO",
    date: "12/06/2026 13:57",
    category: "programacao",
    kind: "modulo",
  },
  {
    name: "Desafio 01: Reforçando sua Autoridade por meio de Artigos | Turma 16",
    institution: "DIO",
    date: "10/06/2026 18:03",
    category: "carreira",
    kind: "extra",
  },
  {
    name: "Semana 03 - DIO Campus Expert | Turma 16",
    institution: "DIO",
    date: "10/06/2026 18:03",
    category: "outros",
    kind: "extra",
  },
  {
    name: "Interfaces e Classes Abstratas com Python",
    institution: "DIO",
    date: "09/06/2026 19:40",
    category: "programacao",
    kind: "modulo",
  },
  {
    name: "Conhecendo Polimorfismo em Python",
    institution: "DIO",
    date: "09/06/2026 18:33",
    category: "programacao",
    kind: "modulo",
  },
  {
    name: "Conquistando Novas Oportunidades com Criação de Conteúdo",
    institution: "DIO",
    date: "09/06/2026 11:54",
    category: "carreira",
    kind: "modulo",
  },
  {
    name: "Aplicando Encapsulamento em Python",
    institution: "DIO",
    date: "08/06/2026 15:37",
    category: "programacao",
    kind: "modulo",
  },
  {
    name: "Aprendendo o Conceito de Herança com Python",
    institution: "DIO",
    date: "08/06/2026 14:33",
    category: "programacao",
    kind: "modulo",
  },
  {
    name: "Introdução à Programação Orientada a Objetos (POO) com Python",
    institution: "DIO",
    date: "05/06/2026 12:41",
    category: "programacao",
    kind: "curso",
    featured: true,
  },
  {
    name: "Onboarding & Fundamentos de Python e Lógica de Programação",
    institution: "DIO",
    date: "02/06/2026 21:57",
    category: "programacao",
    kind: "extra",
  },
  {
    name: "Aprendendo a Utilizar Dicionários em Python",
    institution: "DIO",
    date: "02/06/2026 21:53",
    category: "programacao",
    kind: "modulo",
  },
  {
    name: "Semana 02 - DIO Campus Expert | Turma 16",
    institution: "DIO",
    date: "02/06/2026 14:03",
    category: "outros",
    kind: "extra",
  },
  {
    name: "Construindo o seu Futuro Tech com o Santander",
    institution: "DIO",
    date: "02/06/2026 14:03",
    category: "outros",
    kind: "modulo",
  },
  {
    name: "Conhecendo Tuplas em Python",
    institution: "DIO",
    date: "02/06/2026 12:33",
    category: "programacao",
    kind: "modulo",
  },
  {
    name: "Trabalhando com Listas em Python",
    institution: "DIO",
    date: "02/06/2026 12:01",
    category: "programacao",
    kind: "modulo",
  },
  {
    name: "Manipulando Strings com Python",
    institution: "DIO",
    date: "28/05/2026 11:12",
    category: "programacao",
    kind: "modulo",
  },
  {
    name: "Estruturas Condicionais e de Repetição em Python",
    institution: "DIO",
    date: "26/05/2026 10:16",
    category: "programacao",
    kind: "modulo",
  },
  {
    name: "Tipos de Operadores com Python",
    institution: "DIO",
    date: "25/05/2026 12:32",
    category: "programacao",
    kind: "modulo",
  },
  {
    name: "Semana 01 - DIO Campus Expert Turma 16",
    institution: "DIO",
    date: "25/05/2026 11:12",
    category: "outros",
    kind: "extra",
  },
  {
    name: "Tutorial Prêmios e Bônus | DIO Campus Expert Turma 16",
    institution: "DIO",
    date: "25/05/2026 11:12",
    category: "carreira",
    kind: "extra",
  },
  {
    name: "Como Liderar em um Mundo \"Resetado\" pela IA?",
    institution: "DIO",
    date: "25/05/2026 11:12",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Conhecendo a Linguagem de Programação Python",
    institution: "DIO",
    date: "22/05/2026 14:09",
    category: "programacao",
    kind: "modulo",
  },
  {
    name: "Onboarding | Boas-vindas ao DIO Campus Expert Turma 16",
    institution: "DIO",
    date: "20/05/2026 21:08",
    category: "outros",
    kind: "extra",
  },
  {
    name: "Ambiente de Desenvolvimento e Primeiros Passos com Python",
    institution: "DIO",
    date: "18/05/2026 12:01",
    category: "programacao",
    kind: "modulo",
  },
  {
    name: "Introdução ao Luizalabs - Back-end com Python - 2º Edição",
    institution: "DIO",
    date: "18/05/2026 11:01",
    category: "backend",
    kind: "modulo",
  },
  {
    name: "Santander AI Youtube Creator",
    institution: "DIO",
    date: "13/05/2026 10:15",
    category: "outros",
    kind: "modulo",
  },
  {
    name: "Desafio Final: Canal ativado. Creator em operação.",
    institution: "DIO",
    date: "13/05/2026 10:15",
    category: "outros",
    kind: "extra",
  },
  {
    name: "Encerramento, propósito e próxima etapa da jornada",
    institution: "DIO",
    date: "13/05/2026 09:55",
    category: "carreira",
    kind: "extra",
  },
  {
    name: "Pitch autoral & apresentação oficial do canal",
    institution: "DIO",
    date: "12/05/2026 19:02",
    category: "outros",
    kind: "extra",
  },
  {
    name: "Consolide seu sistema. enxergue o canal como um todo vivo",
    institution: "DIO",
    date: "12/05/2026 12:15",
    category: "outros",
    kind: "modulo",
  },
  {
    name: "Checkpoint: revisão do canal e consistência visual com copilotos de IA",
    institution: "DIO",
    date: "12/05/2026 11:20",
    category: "ia",
    kind: "extra",
  },
  {
    name: "Dossiê de Verificação Operacional",
    institution: "DIO",
    date: "12/05/2026 11:19",
    category: "outros",
    kind: "extra",
  },
  {
    name: "Prepare seu canal para o mundo",
    institution: "DIO",
    date: "12/05/2026 11:05",
    category: "outros",
    kind: "modulo",
  },
  {
    name: "Autoavaliação e pensamento crítico visual",
    institution: "DIO",
    date: "12/05/2026 10:44",
    category: "outros",
    kind: "extra",
  },
  {
    name: "Revisão técnica e compliance IA",
    institution: "DIO",
    date: "11/05/2026 19:57",
    category: "ia",
    kind: "extra",
  },
  {
    name: "Seu canal, sua cara! Identidade visual, branding e thumbnails com IA como copiloto",
    institution: "DIO",
    date: "11/05/2026 19:28",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Experiência visual completa",
    institution: "DIO",
    date: "11/05/2026 19:28",
    category: "outros",
    kind: "modulo",
  },
  {
    name: "Estilo, percepção e experiência de marca (IA + multissensorial)",
    institution: "DIO",
    date: "11/05/2026 19:10",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Kit Visual IA do Creator",
    institution: "DIO",
    date: "11/05/2026 11:24",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Design de capa, thumbnail e padrão estético de canal",
    institution: "DIO",
    date: "11/05/2026 10:55",
    category: "outros",
    kind: "modulo",
  },
  {
    name: "Moodboard IA e DNA visual",
    institution: "DIO",
    date: "09/05/2026 14:12",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Fundamentos de identidade visual e branding pessoal",
    institution: "DIO",
    date: "09/05/2026 13:10",
    category: "outros",
    kind: "modulo",
  },
  {
    name: "Aprenda a contar histórias que viralizam: storytelling e roteirização com IA",
    institution: "DIO",
    date: "09/05/2026 12:03",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Origem & voz com IA",
    institution: "DIO",
    date: "09/05/2026 12:03",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Emoção, ritmo e presença narrativa",
    institution: "DIO",
    date: "09/05/2026 11:50",
    category: "outros",
    kind: "modulo",
  },
  {
    name: "Roteirização e voz criativa com IA",
    institution: "DIO",
    date: "09/05/2026 11:09",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Fundamentos do storytelling criativo",
    institution: "DIO",
    date: "07/05/2026 12:47",
    category: "outros",
    kind: "modulo",
  },
  {
    name: "Setup e fundamentos: hora de montar a base do seu canal",
    institution: "DIO",
    date: "06/05/2026 14:13",
    category: "outros",
    kind: "modulo",
  },
  {
    name: "Desafio de Projeto (M1–M3)",
    institution: "DIO",
    date: "06/05/2026 14:13",
    category: "outros",
    kind: "extra",
  },
  {
    name: "Estrutura e rotina do canal em escala",
    institution: "DIO",
    date: "06/05/2026 13:57",
    category: "outros",
    kind: "modulo",
  },
  {
    name: "Upload Técnico e Validação IA",
    institution: "DIO",
    date: "06/05/2026 11:38",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "SEO e otimização Inteligente",
    institution: "DIO",
    date: "06/05/2026 11:18",
    category: "outros",
    kind: "modulo",
  },
  {
    name: "Setup IA Ready",
    institution: "DIO",
    date: "05/05/2026 13:03",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Criação e estrutura técnica do canal",
    institution: "DIO",
    date: "05/05/2026 10:50",
    category: "outros",
    kind: "modulo",
  },
  {
    name: "Crie sua Estratégia e seu plano de conteúdo",
    institution: "DIO",
    date: "04/05/2026 15:05",
    category: "outros",
    kind: "modulo",
  },
  {
    name: "Mapa de Conteúdo IA de 30 Dias",
    institution: "DIO",
    date: "04/05/2026 15:05",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Planejamento estratégico de conteúdo na prática",
    institution: "DIO",
    date: "04/05/2026 14:45",
    category: "outros",
    kind: "modulo",
  },
  {
    name: "Seu DNA Criativo IA, propósito, persona e arquétipo em ação",
    institution: "DIO",
    date: "04/05/2026 13:55",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Pensamento estrategista Creator IA",
    institution: "DIO",
    date: "04/05/2026 13:10",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Bem-vindo ao AI YouTube Creator: sua jornada começa aqui",
    institution: "DIO",
    date: "04/05/2026 11:50",
    category: "carreira",
    kind: "extra",
  },
  {
    name: "Meu Co-Pilot IA Creator no Notion",
    institution: "DIO",
    date: "04/05/2026 11:50",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Crie seu cockpit de criação",
    institution: "DIO",
    date: "04/05/2026 10:23",
    category: "outros",
    kind: "modulo",
  },
  {
    name: "Formação SQL Database Specialist",
    institution: "DIO",
    date: "02/05/2026 20:41",
    category: "banco-de-dados",
    kind: "curso",
    featured: true,
  },
  {
    name: "Transações & Gerenciamento de Banco De Dados Com no MySQL",
    institution: "DIO",
    date: "02/05/2026 20:41",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Avalie a Formação SQL Database Specialist",
    institution: "DIO",
    date: "02/05/2026 20:41",
    category: "banco-de-dados",
    kind: "extra",
  },
  {
    name: "Materiais Complementares - Trabalhando com Transações, Controle de Concorrência e Técnicas de Recuperação de Banco de dados no MySQL",
    institution: "DIO",
    date: "02/05/2026 20:17",
    category: "banco-de-dados",
    kind: "extra",
  },
  {
    name: "Criando Transações, Executando Backup e Recovery de Banco de Dados",
    institution: "DIO",
    date: "02/05/2026 20:06",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Técnicas de Recuperação em Dados de Banco de Dados com MySQL",
    institution: "DIO",
    date: "01/05/2026 16:58",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Controle de Concorrência em Banco de Dados com MySQL",
    institution: "DIO",
    date: "30/04/2026 15:59",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Start & onboarding",
    institution: "DIO",
    date: "30/04/2026 12:07",
    category: "outros",
    kind: "extra",
  },
  {
    name: "Transações de Banco de Dados com MySQL",
    institution: "DIO",
    date: "29/04/2026 15:36",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Técnicas Avançadas em Banco de Dados com MySQL",
    institution: "DIO",
    date: "29/04/2026 11:37",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "O Mapa de Sucesso Para a Carreira de Dados",
    institution: "DIO",
    date: "29/04/2026 11:37",
    category: "carreira",
    kind: "modulo",
  },
  {
    name: "Materiais Complementares -Técnicas Avançadas de Banco de Dados",
    institution: "DIO",
    date: "29/04/2026 10:11",
    category: "banco-de-dados",
    kind: "extra",
  },
  {
    name: "Personalizando Acessos e Automatizando ações no MySQL",
    institution: "DIO",
    date: "28/04/2026 23:02",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Personalizando o Banco de Dados com Índices e Procedures",
    institution: "DIO",
    date: "28/04/2026 22:24",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Normalização em Banco de Dados",
    institution: "DIO",
    date: "28/04/2026 19:43",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Fundamentos de Indexação em SGBDs com MySQL",
    institution: "DIO",
    date: "28/04/2026 17:25",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Overview sobre Automatização de Ações com Triggers no MySQL",
    institution: "DIO",
    date: "28/04/2026 15:16",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Explorando Lógica de Programação com SQL Dinâmico",
    institution: "DIO",
    date: "28/04/2026 13:55",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Explorando Cláusulas de DDL e Esquemas de Banco de Dados no MySQL",
    institution: "DIO",
    date: "27/04/2026 22:05",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Personalizando acessos com Views",
    institution: "DIO",
    date: "27/04/2026 15:02",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Explorando a Linguagem de Consulta a Banco de Dados SQL",
    institution: "DIO",
    date: "26/04/2026 02:14",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Materiais complementares - Explorando a Linguagem de Consulta à Banco de Dados SQL",
    institution: "DIO",
    date: "26/04/2026 02:14",
    category: "banco-de-dados",
    kind: "extra",
  },
  {
    name: "Construa um Projeto Lógico de Banco de Dados do Zero",
    institution: "DIO",
    date: "26/04/2026 02:11",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Construindo seu Primeiro Projeto Lógico de Banco de Dados",
    institution: "DIO",
    date: "26/04/2026 01:55",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Agrupando Registros e Tabelas com Join Statement",
    institution: "DIO",
    date: "24/04/2026 16:02",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Criando Queries com Funções e Cláusulas de Agrupamentos",
    institution: "DIO",
    date: "24/04/2026 14:03",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Explorando Queries com SQL",
    institution: "DIO",
    date: "22/04/2026 18:00",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Primeiros Passos com SQL",
    institution: "DIO",
    date: "21/04/2026 17:43",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Modelo Relacional e Mapeamento Relacional com Banco de Dados",
    institution: "DIO",
    date: "17/04/2026 01:25",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Modelo de Entidade Relacional com Banco De Dados",
    institution: "DIO",
    date: "16/04/2026 15:50",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Materiais complementares - Modelagem de BD com Modelo Entidade e Relacionamento",
    institution: "DIO",
    date: "16/04/2026 15:50",
    category: "banco-de-dados",
    kind: "extra",
  },
  {
    name: "Construindo um Esquema Conceitual para Banco De dados",
    institution: "DIO",
    date: "16/04/2026 15:21",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Refinando um Projeto Conceitual de Banco de Dados – E-COMMERCE",
    institution: "DIO",
    date: "16/04/2026 14:20",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Encerramento DIO Campus Expert Turma 15",
    institution: "DIO",
    date: "16/04/2026 12:44",
    category: "outros",
    kind: "extra",
  },
  {
    name: "Modelo Relacionamento de Entidade Aprimorado com Banco de Dados",
    institution: "DIO",
    date: "15/04/2026 22:09",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Modelo de Entidade Relacionamento com Banco de Dados",
    institution: "DIO",
    date: "15/04/2026 20:27",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Semana 07 - DIO Campus Expert | Turma 15",
    institution: "DIO",
    date: "15/04/2026 18:37",
    category: "outros",
    kind: "extra",
  },
  {
    name: "Transforme a sua Trajetória em uma Carreira Global",
    institution: "DIO",
    date: "15/04/2026 18:37",
    category: "carreira",
    kind: "extra",
  },
  {
    name: "Fundamentos de Modelagem e Projeto de Banco de Dados",
    institution: "DIO",
    date: "13/04/2026 17:03",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Fundamentos de Banco de Dados",
    institution: "DIO",
    date: "13/04/2026 15:13",
    category: "banco-de-dados",
    kind: "curso",
    featured: true,
  },
  {
    name: "Materiais complementares - Fundamentos de Banco de Dados",
    institution: "DIO",
    date: "13/04/2026 15:13",
    category: "banco-de-dados",
    kind: "extra",
  },
  {
    name: "Arquitetura de Banco de Dados",
    institution: "DIO",
    date: "13/04/2026 15:12",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Continue a sua Jornada como Protagonista!",
    institution: "DIO",
    date: "12/04/2026 12:46",
    category: "carreira",
    kind: "extra",
  },
  {
    name: "Desafio 01 | DIO Campus Expert - Turma 14",
    institution: "DIO",
    date: "10/04/2026 13:59",
    category: "outros",
    kind: "extra",
  },
  {
    name: "Passo a Passo para Gerar mais Autoridade para o seu Perfil",
    institution: "DIO",
    date: "07/04/2026 21:00",
    category: "carreira",
    kind: "modulo",
  },
  {
    name: "Modelagem de Dados para Banco de Dados",
    institution: "DIO",
    date: "06/04/2026 15:45",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Semana 05 - DIO Campus Expert | Turma 15",
    institution: "DIO",
    date: "06/04/2026 01:22",
    category: "outros",
    kind: "extra",
  },
  {
    name: "Semana 03 - DIO Campus Expert | Turma 15",
    institution: "DIO",
    date: "06/04/2026 01:22",
    category: "outros",
    kind: "extra",
  },
  {
    name: "Armazenamento e Banco de Dados no Azure",
    institution: "DIO",
    date: "06/04/2026 01:22",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Contêineres e Identidade no Azure",
    institution: "DIO",
    date: "06/04/2026 01:22",
    category: "cloud",
    kind: "modulo",
  },
  {
    name: "Segurança e Gerenciamento de API",
    institution: "DIO",
    date: "06/04/2026 01:22",
    category: "cloud",
    kind: "modulo",
  },
  {
    name: "Soluções Baseadas em Eventos e Mensagens",
    institution: "DIO",
    date: "06/04/2026 01:22",
    category: "cloud",
    kind: "modulo",
  },
  {
    name: "Monitoramento e Cache no Azure",
    institution: "DIO",
    date: "06/04/2026 01:22",
    category: "cloud",
    kind: "modulo",
  },
  {
    name: "Simulado Preparatório o Exame AZ-204",
    institution: "DIO",
    date: "06/04/2026 01:22",
    category: "cloud",
    kind: "extra",
  },
  {
    name: "Mapa de Oportunidades com IA no seu Dia a Dia",
    institution: "DIO",
    date: "04/04/2026 03:39",
    category: "ia",
    kind: "extra",
  },
  {
    name: "Semana 06 - DIO Campus Expert | Turma 15",
    institution: "DIO",
    date: "02/04/2026 18:38",
    category: "outros",
    kind: "extra",
  },
  {
    name: "Construindo o seu Futuro Tech com o Grupo Santander",
    institution: "DIO",
    date: "02/04/2026 18:38",
    category: "outros",
    kind: "modulo",
  },
  {
    name: "Bônus: Montando um portfólio para decolar a sua carreira tech!",
    institution: "DIO",
    date: "02/04/2026 18:37",
    category: "carreira",
    kind: "extra",
  },
  {
    name: "Desafio 02: Escalando Oportunidades com seu Portfólio de Projetos",
    institution: "DIO",
    date: "31/03/2026 20:05",
    category: "carreira",
    kind: "extra",
  },
  {
    name: "Dicas Práticas para Escrever seu Primeiro Artigo",
    institution: "DIO",
    date: "31/03/2026 18:03",
    category: "carreira",
    kind: "extra",
  },
  {
    name: "O que você pode aprender com o Nina Talks?",
    institution: "DIO",
    date: "27/03/2026 13:53",
    category: "carreira",
    kind: "modulo",
  },
  {
    name: "Estruturando o seu Portfólio para atrair Novas Oportunidade",
    institution: "DIO",
    date: "23/03/2026 21:58",
    category: "carreira",
    kind: "modulo",
  },
  {
    name: "Sistemas de Gerenciamento de Banco de Dados",
    institution: "DIO",
    date: "20/03/2026 21:49",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Compartilhando o seu Conhecimento no DIO Campus Expert!",
    institution: "DIO",
    date: "19/03/2026 20:13",
    category: "carreira",
    kind: "modulo",
  },
  {
    name: "Suas Ideias merecem ser Compartilhadas!",
    institution: "DIO",
    date: "19/03/2026 18:55",
    category: "carreira",
    kind: "modulo",
  },
  {
    name: "Desafio 01: Reforçando sua Autoridade por meio de Artigos",
    institution: "DIO",
    date: "18/03/2026 16:35",
    category: "carreira",
    kind: "extra",
  },
  {
    name: "Introdução a Banco de Dados",
    institution: "DIO",
    date: "17/03/2026 18:58",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Conseguindo seu Primeiro Freelance em Tecnologia",
    institution: "DIO",
    date: "16/03/2026 17:01",
    category: "carreira",
    kind: "modulo",
  },
  {
    name: "Comunicação Estratégica para Profissionais Tech",
    institution: "DIO",
    date: "10/03/2026 20:08",
    category: "carreira",
    kind: "modulo",
  },
  {
    name: "Semana 02 - DIO Campus Expert | Turma 15",
    institution: "DIO",
    date: "09/03/2026 12:20",
    category: "outros",
    kind: "extra",
  },
  {
    name: "Portfólio e Perfil para Acelerar sua Carreira em Tech",
    institution: "DIO",
    date: "09/03/2026 12:20",
    category: "carreira",
    kind: "modulo",
  },
  {
    name: "LinkedIn e Vagas de TI: Como Engajar, Conectar e ser Contratado?",
    institution: "DIO",
    date: "02/03/2026 16:30",
    category: "carreira",
    kind: "modulo",
  },
  {
    name: "Tutorial | Como Ganhar Prêmios e Bônus Exclusivos do DIO Campus Expert Turma 15",
    institution: "DIO",
    date: "02/03/2026 15:24",
    category: "carreira",
    kind: "extra",
  },
  {
    name: "Semana 01 - Liberado em 23/02",
    institution: "DIO",
    date: "27/02/2026 10:52",
    category: "outros",
    kind: "extra",
  },
  {
    name: "Como Liderar em um Mundo \"Resetado\" pela IA?",
    institution: "DIO",
    date: "27/02/2026 10:52",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Boas-vindas ao DIO Campus Expert Turma 15",
    institution: "DIO",
    date: "20/02/2026 11:17",
    category: "outros",
    kind: "extra",
  },
  {
    name: "Certificações Microsoft na Prática: Como Acelerar Sua Carreira em Tecnologia",
    institution: "DIO",
    date: "13/02/2026 11:31",
    category: "carreira",
    kind: "modulo",
  },
  {
    name: "Microsoft Certification Challenge #5 - AZ-204",
    institution: "DIO",
    date: "12/02/2026 09:55",
    category: "cloud",
    kind: "modulo",
  },
  {
    name: "Copilot, além da IDE",
    institution: "DIO",
    date: "07/02/2026 21:22",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Domine a Engenharia de Prompt com o GitHub Copilot",
    institution: "DIO",
    date: "05/02/2026 19:19",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Conteúdo Oficial Recomendado do GitHub Copilot",
    institution: "DIO",
    date: "28/01/2026 17:21",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Copilot Chat: Como Utilizar?",
    institution: "DIO",
    date: "28/01/2026 17:06",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Bases de Prompt Engineering para o GitHub Copilot",
    institution: "DIO",
    date: "22/01/2026 11:54",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Primeiros Passos com o GitHub Copilot: Um Guia Essencial",
    institution: "DIO",
    date: "12/12/2025 12:58",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Configurando e Usando o GitHub Copilot",
    institution: "DIO",
    date: "12/12/2025 12:58",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Live de Lançamento: Adotando o GitHub Copilot e o Novo Fluxo de Trabalho",
    institution: "DIO",
    date: "12/12/2025 10:33",
    category: "ia",
    kind: "extra",
  },
  {
    name: "O que é o GitHub Copilot?",
    institution: "DIO",
    date: "08/12/2025 19:22",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Aprimorando seu Desenvolvimento com o GitHub Copilot: o Poder de Ter um Copiloto em seu Fluxo de Trabalho",
    institution: "DIO",
    date: "02/12/2025 16:46",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Inicializando Projetos Node.js",
    institution: "DIO",
    date: "02/09/2025 12:38",
    category: "backend",
    kind: "modulo",
  },
  {
    name: "Instalando Ambiente de Desenvolvimento Node.js",
    institution: "DIO",
    date: "02/09/2025 09:23",
    category: "backend",
    kind: "modulo",
  },
  {
    name: "Live de Lançamento: Bootcamp meutudo - Mobile Developer",
    institution: "DIO",
    date: "01/09/2025 22:00",
    category: "outros",
    kind: "extra",
  },
  {
    name: "Recriando o ChatGPT com Nodejs e TypeScript",
    institution: "DIO",
    date: "01/09/2025 22:00",
    category: "backend",
    kind: "modulo",
  },
  {
    name: "Introdução ao Node.js",
    institution: "DIO",
    date: "01/09/2025 21:38",
    category: "backend",
    kind: "curso",
  },
  {
    name: "Bem-Vindo ao Mundo do Node.js",
    institution: "DIO",
    date: "28/08/2025 19:46",
    category: "backend",
    kind: "modulo",
  },
  {
    name: "Desenvolvimento Mobile com a meutudo",
    institution: "DIO",
    date: "02/07/2025 11:51",
    category: "outros",
    kind: "modulo",
  },
  {
    name: "Criando Pipelines com GitHub Actions de Alta Performance",
    institution: "DIO",
    date: "14/04/2025 11:04",
    category: "devops",
    kind: "modulo",
  },
  {
    name: "Como trabalhar com Contâiners de maneira eficiente com Docker",
    institution: "DIO",
    date: "14/04/2025 11:04",
    category: "devops",
    kind: "curso",
  },
  {
    name: "Papo com o RH: O Perfil Profissional de Dev que o Bradesco procura",
    institution: "DIO",
    date: "14/04/2025 11:03",
    category: "carreira",
    kind: "modulo",
  },
  {
    name: "Live de Lançamento: Bradesco - Java Cloud Native",
    institution: "DIO",
    date: "13/03/2025 14:00",
    category: "programacao",
    kind: "extra",
  },
  {
    name: "Ambiente de Desenvolvimento Java",
    institution: "DIO",
    date: "27/02/2025 13:13",
    category: "programacao",
    kind: "modulo",
  },
  {
    name: "Introdução à Plataforma Java",
    institution: "DIO",
    date: "27/02/2025 12:27",
    category: "programacao",
    kind: "modulo",
  },
  {
    name: "Introdução ao Java Cloud Native com o Bradesco",
    institution: "DIO",
    date: "27/02/2025 12:04",
    category: "programacao",
    kind: "curso",
  },
  {
    name: "Trabalhando com Nuvem Híbrida com Azure Red Hat OpenShift (ARO)",
    institution: "DIO",
    date: "27/02/2025 11:56",
    category: "cloud",
    kind: "modulo",
  },
  {
    name: "Como Utilizar GitHub Copilot para Produtividade",
    institution: "DIO",
    date: "27/02/2025 11:36",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Bootcamp Microsoft Certification Challenge #2 AZ-204",
    institution: "DIO",
    date: "21/01/2025 19:15",
    category: "cloud",
    kind: "modulo",
  },
  {
    name: "Simulado Preparatório o Exame AZ-204",
    institution: "DIO",
    date: "21/01/2025 19:15",
    category: "cloud",
    kind: "extra",
  },
  {
    name: "Monitoramento e Cache no Azure",
    institution: "DIO",
    date: "21/01/2025 19:08",
    category: "cloud",
    kind: "modulo",
  },
  {
    name: "Criando um Gerenciador de Catálogos da Netflix com Azure Functions e Banco de Dados",
    institution: "DIO",
    date: "21/01/2025 19:08",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Implementando Cache para Soluções",
    institution: "DIO",
    date: "21/01/2025 15:21",
    category: "cloud",
    kind: "modulo",
  },
  {
    name: "Como Fazer o Deploy de uma API na Nuvem na Prática",
    institution: "DIO",
    date: "21/01/2025 15:07",
    category: "cloud",
    kind: "modulo",
  },
  {
    name: "Soluções Baseadas em Eventos e Mensagens",
    institution: "DIO",
    date: "21/01/2025 15:07",
    category: "cloud",
    kind: "modulo",
  },
  {
    name: "Segurança e Gerenciamento de API",
    institution: "DIO",
    date: "21/01/2025 13:39",
    category: "cloud",
    kind: "modulo",
  },
  {
    name: "Criando um Microsserviço Serverless para Validação de CPF",
    institution: "DIO",
    date: "21/01/2025 13:39",
    category: "cloud",
    kind: "modulo",
  },
  {
    name: "Solucionando Problemas usando o Application Insights",
    institution: "DIO",
    date: "21/01/2025 12:41",
    category: "cloud",
    kind: "modulo",
  },
  {
    name: "Desenvolvendo Soluções Baseadas em Mensagem",
    institution: "DIO",
    date: "21/01/2025 12:23",
    category: "cloud",
    kind: "modulo",
  },
  {
    name: "Desenvolvendo Soluções Baseadas em Eventos",
    institution: "DIO",
    date: "21/01/2025 12:12",
    category: "cloud",
    kind: "modulo",
  },
  {
    name: "Desenvolvendo Soluções de Gerenciamento de API",
    institution: "DIO",
    date: "21/01/2025 12:02",
    category: "cloud",
    kind: "modulo",
  },
  {
    name: "Implementando Soluções de Nuvem Seguras",
    institution: "DIO",
    date: "21/01/2025 11:53",
    category: "cloud",
    kind: "modulo",
  },
  {
    name: "Contêineres e Identidade no Azure",
    institution: "DIO",
    date: "21/01/2025 11:40",
    category: "cloud",
    kind: "modulo",
  },
  {
    name: "Implementando a Plataforma de Identidade da Microsoft",
    institution: "DIO",
    date: "21/01/2025 11:40",
    category: "cloud",
    kind: "modulo",
  },
  {
    name: "Implementando Aplicativos de Contêiner no Azure",
    institution: "DIO",
    date: "21/01/2025 11:32",
    category: "cloud",
    kind: "modulo",
  },
  {
    name: "Armazenamento e Banco de Dados no Azure",
    institution: "DIO",
    date: "20/01/2025 20:44",
    category: "banco-de-dados",
    kind: "modulo",
  },
  {
    name: "Trabalhando com o Azure Cosmos DB",
    institution: "DIO",
    date: "20/01/2025 19:40",
    category: "cloud",
    kind: "modulo",
  },
  {
    name: "Explorando o Armazenamento de Blobs do Azure",
    institution: "DIO",
    date: "20/01/2025 19:24",
    category: "cloud",
    kind: "modulo",
  },
  {
    name: "Desenvolvimento de Aplicativos Web e Funções no Azure",
    institution: "DIO",
    date: "20/01/2025 14:58",
    category: "cloud",
    kind: "modulo",
  },
  {
    name: "Versionamento de Código com Git e GitHub",
    institution: "DIO",
    date: "20/01/2025 14:58",
    category: "git-github",
    kind: "curso",
    featured: true,
  },
  {
    name: "Explorando o Serviço de Aplicativo do Azure",
    institution: "DIO",
    date: "20/01/2025 12:00",
    category: "cloud",
    kind: "modulo",
  },
  {
    name: "Implementando o Azure Functions",
    institution: "DIO",
    date: "20/01/2025 10:59",
    category: "cloud",
    kind: "modulo",
  },
  {
    name: "Introdução a AZ-204 com a Microsoft",
    institution: "DIO",
    date: "18/01/2025 22:45",
    category: "cloud",
    kind: "modulo",
  },
  {
    name: "Live de Lançamento: Bootcamp Microsoft Certification Challenge #2 AZ-204",
    institution: "DIO",
    date: "18/01/2025 22:39",
    category: "cloud",
    kind: "extra",
  },
  {
    name: "Microsoft - Fundamentos de IA",
    institution: "DIO",
    date: "18/01/2025 20:12",
    category: "ia",
    kind: "curso",
  },
  {
    name: "Aplicações de Visão Computacional no Azure",
    institution: "DIO",
    date: "18/01/2025 20:12",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Conhecendo os Serviços de Inteligência Artificial no Microsoft Azure",
    institution: "DIO",
    date: "18/01/2025 16:42",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Azure Cognitive Search: Utilizando AI Search para indexação e consulta de Dados",
    institution: "DIO",
    date: "17/01/2025 15:07",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Informação de Documentos e Mineração de Conhecimento no Azure",
    institution: "DIO",
    date: "17/01/2025 15:07",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Explorando os Recursos de IA Generativa com Copilot e OpenAI",
    institution: "DIO",
    date: "17/01/2025 14:51",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Fundamentos da IA Generativa no Azure",
    institution: "DIO",
    date: "17/01/2025 14:51",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Trabalhando com Serviços Azure OpenAI",
    institution: "DIO",
    date: "17/01/2025 13:53",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Preparação para o Exame Microsoft Azure AI-900",
    institution: "DIO",
    date: "17/01/2025 12:55",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Dicas MVP Microsoft para Tirar sua Certificação",
    institution: "DIO",
    date: "17/01/2025 12:55",
    category: "outros",
    kind: "extra",
  },
  {
    name: "Inteligência de Documentos de IA do Azure",
    institution: "DIO",
    date: "17/01/2025 12:42",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Análise de Sentimentos com Language Studio no Azure AI",
    institution: "DIO",
    date: "16/01/2025 20:53",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Processamento de Linguagem Natural e IA Conversacional",
    institution: "DIO",
    date: "16/01/2025 20:53",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Conceitos de Processamento de Linguagem Natural",
    institution: "DIO",
    date: "16/01/2025 11:00",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Reconhecimento Facial e transformação de imagens em Dados no Azure ML",
    institution: "DIO",
    date: "16/01/2025 04:01",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Conceitos de Visão Computacional",
    institution: "DIO",
    date: "15/01/2025 09:39",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Trabalhando com Machine Learning na Prática no Azure ML",
    institution: "DIO",
    date: "13/01/2025 16:01",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Fundamentos de IA no Microsoft Azure",
    institution: "DIO",
    date: "13/01/2025 16:01",
    category: "ia",
    kind: "curso",
    featured: true,
  },
  {
    name: "Desafios de Projetos: Crie Um Portfólio Vencedor",
    institution: "DIO",
    date: "13/01/2025 14:42",
    category: "carreira",
    kind: "modulo",
  },
  {
    name: "Fundamentos do Aprendizado de Máquina",
    institution: "DIO",
    date: "13/01/2025 14:01",
    category: "ia",
    kind: "curso",
  },
  {
    name: "Conceitos Fundamentais de IA",
    institution: "DIO",
    date: "13/01/2025 13:00",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Introdução a AI-900 com a Microsoft",
    institution: "DIO",
    date: "13/01/2025 11:35",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "CAIXA - IA Generativa com Microsoft Copilot",
    institution: "DIO",
    date: "11/01/2025 14:17",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Como trabalhar com Prompts e Linguagem Natural",
    institution: "DIO",
    date: "11/01/2025 14:17",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Trabalhando com Ferramentas Copilot",
    institution: "DIO",
    date: "12/12/2024 22:23",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "GitHub Copilot: Como ter mais IA te ajudando na produtividade do dia a dia",
    institution: "DIO",
    date: "12/12/2024 22:23",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Microsoft Copilot Studio: Construa Seu Próprio Copilot Customizado",
    institution: "DIO",
    date: "12/12/2024 21:34",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Engenharia de Prompt: Potencializando o Uso de IA Generativa",
    institution: "DIO",
    date: "02/12/2024 20:46",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Introdução a Inteligência Artificial Generativa",
    institution: "DIO",
    date: "02/12/2024 20:46",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Desafios de Responsabilidade Ética e Social com IA Generativa",
    institution: "DIO",
    date: "02/12/2024 20:46",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Green Software Development - Português",
    institution: "DIO",
    date: "19/11/2024 18:25",
    category: "outros",
    kind: "curso",
  },
  {
    name: "Green Software Development - English",
    institution: "DIO",
    date: "19/11/2024 12:38",
    category: "outros",
    kind: "modulo",
  },
  {
    name: "Inteligência Artificial Aplicada",
    institution: "DIO",
    date: "19/11/2024 11:37",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "O Cidadão Desenvolvedor CAIXA e as Ferramentas de IA",
    institution: "DIO",
    date: "19/11/2024 11:37",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Criando um Podcast com IAs Generativas",
    institution: "DIO",
    date: "18/11/2024 10:53",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Projetos Práticos com IA",
    institution: "DIO",
    date: "18/11/2024 10:53",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Como organizar sua vida Financeira com Planilhas Inteligentes e IA",
    institution: "DIO",
    date: "18/11/2024 10:51",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Criando um Ebook com ChatGPT & MidJourney",
    institution: "DIO",
    date: "15/11/2024 13:11",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Act Commands - Seu ChatGPT como Assistente Virtual",
    institution: "DIO",
    date: "15/11/2024 10:18",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Prompts Assertivos para ChatGPT",
    institution: "DIO",
    date: "14/11/2024 19:55",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Visão Computacional",
    institution: "DIO",
    date: "14/11/2024 12:48",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Desafio CAIXA - Projetos IA Powered",
    institution: "DIO",
    date: "14/11/2024 11:50",
    category: "ia",
    kind: "extra",
  },
  {
    name: "Avalie este Bootcamp",
    institution: "DIO",
    date: "14/11/2024 11:50",
    category: "outros",
    kind: "extra",
  },
  {
    name: "Processamento de Linguagem Natural",
    institution: "DIO",
    date: "14/11/2024 11:39",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Algoritmos e Aprendizado de Máquina",
    institution: "DIO",
    date: "14/11/2024 11:04",
    category: "programacao",
    kind: "modulo",
  },
  {
    name: "O que são IAs Generativas",
    institution: "DIO",
    date: "14/11/2024 09:55",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Desafios de Código: Aperfeiçoe Sua Lógica e Pensamento Computacional",
    institution: "DIO",
    date: "13/11/2024 15:20",
    category: "programacao",
    kind: "modulo",
  },
  {
    name: "Natural ou Fake Natty? Como Vencer na Era das IAs Generativas!",
    institution: "DIO",
    date: "13/11/2024 14:09",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Fundamentos da IA Generativa",
    institution: "DIO",
    date: "13/11/2024 13:18",
    category: "ia",
    kind: "curso",
  },
  {
    name: "Desafio CAIXA - Criando Impacto Social Com IA",
    institution: "DIO",
    date: "13/11/2024 10:47",
    category: "ia",
    kind: "extra",
  },
  {
    name: "Fundamentos de Inteligência Artificial (IA)",
    institution: "DIO",
    date: "12/11/2024 16:36",
    category: "ia",
    kind: "curso",
  },
  {
    name: "Live de Lançamento: Como a CAIXA Está utilizando IA para transformar o Mercado",
    institution: "DIO",
    date: "12/11/2024 16:36",
    category: "ia",
    kind: "extra",
  },
  {
    name: "Aplicações Práticas da Inteligência Artificial",
    institution: "DIO",
    date: "12/11/2024 15:19",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Aplicações e Impacto da IA no Mundo Atual",
    institution: "DIO",
    date: "12/11/2024 11:42",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Introdução à Inteligência Artificial",
    institution: "DIO",
    date: "12/11/2024 01:17",
    category: "ia",
    kind: "modulo",
  },
  {
    name: "Coding The Future CAIXA - Introdução a IA Generativa com Microsoft Copilot",
    institution: "DIO",
    date: "12/11/2024 00:31",
    category: "ia",
    kind: "modulo",
  },
];
