export const glossaryTerms: { term: string; definition: string }[] = [
  { term: "API", definition: "Application Programming Interface — uma forma padronizada de dois sistemas trocarem informação." },
  { term: "Back-End", definition: "A parte de um sistema que roda no servidor: regras de negócio, banco de dados e APIs." },
  { term: "Front-End", definition: "A parte de um sistema com a qual o usuário interage diretamente, geralmente no navegador." },
  { term: "SQL", definition: "Structured Query Language — linguagem usada para consultar e manipular bancos de dados relacionais." },
  { term: "HTTP", definition: "Protocolo usado para comunicação entre cliente e servidor na web." },
  { term: "HTTPS", definition: "Versão do HTTP com criptografia, protegendo os dados trafegados." },
  { term: "DNS", definition: "Domain Name System — traduz nomes de domínio (como um site) em endereços IP." },
  { term: "DHCP", definition: "Protocolo que atribui automaticamente endereços IP a dispositivos em uma rede." },
  { term: "IP", definition: "Internet Protocol — o endereço que identifica um dispositivo em uma rede." },
  { term: "TCP", definition: "Protocolo de transporte confiável, usado para garantir que os dados cheguem completos e na ordem certa." },
  { term: "UDP", definition: "Protocolo de transporte mais rápido, porém sem garantia de entrega — usado quando velocidade importa mais que confiabilidade." },
  { term: "JSON", definition: "Formato leve de troca de dados, muito usado por APIs." },
  { term: "REST", definition: "Um estilo de arquitetura para construir APIs usando os métodos padrão do HTTP." },
  { term: "CRUD", definition: "Create, Read, Update, Delete — as quatro operações básicas sobre dados." },
  { term: "JWT", definition: "JSON Web Token — um formato de token usado para autenticação entre cliente e servidor." },
  { term: "Git", definition: "Sistema de controle de versão que registra o histórico de alterações de um projeto." },
  { term: "GitHub", definition: "Plataforma que hospeda repositórios Git e facilita colaboração em projetos." },
  { term: "Docker", definition: "Ferramenta que empacota uma aplicação e suas dependências em um container isolado e portátil." },
  { term: "Cloud", definition: "Computação em nuvem — uso de servidores e serviços de terceiros pela internet, sem gerenciar hardware próprio." },
  { term: "IA", definition: "Inteligência Artificial — sistemas capazes de realizar tarefas que normalmente exigiriam raciocínio humano." },
  { term: "LLM", definition: "Large Language Model — modelo de IA treinado em grandes volumes de texto para gerar e entender linguagem." },
  { term: "RAG", definition: "Retrieval-Augmented Generation — técnica que busca documentos relevantes antes de gerar uma resposta com IA." },
  { term: "Kafka", definition: "Plataforma de streaming de eventos usada para mover dados em tempo real entre sistemas." },
  { term: "Producer", definition: "No Kafka, o componente que envia (produz) mensagens para um tópico." },
  { term: "Consumer", definition: "No Kafka, o componente que lê (consome) mensagens de um tópico." },
  { term: "Topic", definition: "No Kafka, o canal nomeado para onde mensagens são publicadas e de onde são lidas." },
  { term: "Partition", definition: "Divisão de um tópico Kafka, usada para escalar leitura e escrita em paralelo." },
  { term: "ETL", definition: "Extract, Transform, Load — processo de extrair dados, transformá-los e carregá-los em outro sistema." },
  { term: "ELT", definition: "Extract, Load, Transform — variação do ETL em que a transformação acontece depois da carga dos dados." },
  { term: "SLA", definition: "Service Level Agreement — o prazo combinado para atender e resolver um chamado." },
  { term: "FCR", definition: "First Call Resolution — percentual de chamados resolvidos já no primeiro contato." },
  { term: "MTTR", definition: "Mean Time To Resolve — tempo médio para resolver um incidente." },
];
